<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTqs8fbm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTqs8fbm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTqs8fbm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTqs8fbm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTqs8fbm\appDevDebugProjectContainer([
    'container.build_hash' => 'Tqs8fbm',
    'container.build_id' => '1b801dba',
    'container.build_time' => 1555055055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTqs8fbm');
