<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ekpdjq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ekpdjq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4ekpdjq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4ekpdjq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4ekpdjq\appDevDebugProjectContainer([
    'container.build_hash' => '4ekpdjq',
    'container.build_id' => '6e008439',
    'container.build_time' => 1556789029,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4ekpdjq');
