<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD8ch3qm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD8ch3qm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerD8ch3qm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerD8ch3qm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerD8ch3qm\appDevDebugProjectContainer(array(
    'container.build_hash' => 'D8ch3qm',
    'container.build_id' => 'a915ae6e',
    'container.build_time' => 1554294305,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerD8ch3qm');
